/**
 * This component:
 *   - Adds initial meta content for the site via Helmet
 *   - Adds hot module reloading to the app
 *   - Passes store data into the top-level Layout component
 */
import React from 'react'
import { hot } from 'react-hot-loader/root'
import Helmet from 'react-helmet'
import Layout from './Layout'
import store from '../store'

const { posts, pages } = store

const App = () => (
  <div>
    <Helmet>
      <title>BuddhaBlogTemplate</title>
      <meta
        name="description"
        content="A static blog site generated by BuddhaBlog"
      />
    </Helmet>
    <Layout pages={pages} posts={posts} />
  </div>
)

export default hot(App)
